apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 50050
    targetPort: 50050
  selector:
    app: grpc-server
